import { beforeEach, describe, expect, it, vi } from 'vitest';

const { mockLoadModel } = vi.hoisted(() => ({
  mockLoadModel: vi.fn(),
}));

vi.mock('../../../domain/model/loadModel', () => ({
  loadModel: mockLoadModel,
}));

import { loadContentBootstrapWithFacade } from '../contentBootstrapClient';

const localModel = {
  version: '1.0.0',
  meta: {
    appName: 'Protocolo Bússola',
    version: '1.0',
    scope: 'MVP',
    guardrailEnabled: true,
  },
  uiConfig: {
    designStyle: 'modern',
    cardsRounded: true,
    shadowSoft: true,
    maxQuestionsPerFlow: 8,
    resultLayout: {
      primaryServiceFirst: true,
      secondaryServiceVisible: true,
      collapsibleGuidelines: true,
      institutionalSummaryAutoGenerated: true,
    },
  },
  searchConfig: {
    mode: 'unified',
    includeSynonyms: true,
    fieldsIndexed: ['meta.title'],
  },
  institution: {
    name: 'E.E. Ermelino Matarazzo',
    managementContact: {
      name: 'Gestão',
      phone: '11 0000-0000',
      email: 'gestao@example.com',
    },
  },
};

describe('loadContentBootstrapWithFacade', () => {
  beforeEach(() => {
    vi.resetAllMocks();
    vi.unstubAllEnvs();
  });

  it('uses local fallback when feature flag is disabled', async () => {
    vi.stubEnv('VITE_FEATURE_CONTENT_BOOTSTRAP_API', 'false');
    mockLoadModel.mockReturnValue(localModel);

    const result = await loadContentBootstrapWithFacade();

    expect(result.model.version).toBe('1.0.0');
    expect(result.model.meta.appName).toBe('Protocolo Bússola');
    expect(mockLoadModel).toHaveBeenCalledTimes(1);
  });

  it('uses API payload when feature flag is enabled and response is valid', async () => {
    vi.stubEnv('VITE_FEATURE_CONTENT_BOOTSTRAP_API', 'true');
    mockLoadModel.mockReturnValue(localModel);
    const fetchMock = vi.fn().mockResolvedValue({
      ok: true,
      json: async () => ({
        ok: true,
        traceId: 'trace_123',
        data: {
          model: {
            version: '1.0.1',
            meta: localModel.meta,
            uiConfig: localModel.uiConfig,
            searchConfig: localModel.searchConfig,
            institution: { name: 'Escola API' },
          },
          network: {
            tileUrl: 'https://tiles.example.com/{z}/{x}/{y}.png',
            attributionHtml: 'attrib',
          },
        },
      }),
    });
    vi.stubGlobal('fetch', fetchMock);

    const result = await loadContentBootstrapWithFacade();

    expect(fetchMock).toHaveBeenCalledTimes(1);
    expect(result.model.version).toBe('1.0.1');
    expect(result.model.institution.name).toBe('Escola API');
    expect(mockLoadModel).not.toHaveBeenCalled();
  });

  it('falls back to local bootstrap when API fails', async () => {
    vi.stubEnv('VITE_FEATURE_CONTENT_BOOTSTRAP_API', 'true');
    mockLoadModel.mockReturnValue(localModel);
    vi.stubGlobal(
      'fetch',
      vi.fn().mockResolvedValue({
        ok: false,
        json: async () => ({}),
      }),
    );

    const result = await loadContentBootstrapWithFacade();

    expect(result.model.version).toBe('1.0.0');
    expect(mockLoadModel).toHaveBeenCalledTimes(1);
  });
});
