export interface AppModel {
  meta: {
    appName: string;
    version: string;
    scope: string;
    guardrailEnabled: boolean;
    emergencyButton?: {
      label: string;
      color: string;
      fixed: boolean;
      priorityRouteIds: string[];
    };
  };
  searchConfig?: {
    mode: string;
    includeSynonyms: boolean;
    fieldsIndexed: string[];
  };
  uiConfig?: {
    designStyle: string;
    cardsRounded: boolean;
    shadowSoft: boolean;
    maxQuestionsPerFlow: number;
    resultLayout: {
      primaryServiceFirst: boolean;
      secondaryServiceVisible: boolean;
      collapsibleGuidelines: boolean;
      institutionalSummaryAutoGenerated: boolean;
    };
  };
  guardrail: {
    questions: GuardrailQuestion[];
  };
  categories: Category[];
  flows: Flow[];
  services: Service[];
  orientationBlocks: OrientationBlock[];
  summaryTemplate: {
    title: string;
    structure: string[];
  };
  institution: {
    name: string;
    managementContact: {
      name: string;
      phone: string;
      email: string;
    };
  };
}

export interface GuardrailQuestion {
  id: string;
  text: string;
  type: 'boolean';
  ifTrue: string;
}

export interface Category {
  id: string;
  label: string;
  description?: string;
  icon: string;
  color?: string;
  subcategories: Array<{ id: string; label: string }>;
  isEmergencyCategory?: boolean;
}

export interface Flow {
  meta: {
    id: string;
    categoryId: string; // Added to maintain relationship
    subcategory: string;
    type: 'standard' | 'medical_emergency' | 'security_emergency';
    title: string;
    keywords: string[];
  };
  riskModel: {
    usedLevels: string[];
    defaultLevel: string;
  };
  triage: {
    maxQuestions: number;
    questions: TriageQuestion[];
  };
  results: Record<string, TriageResult>;
}

export interface TriageQuestion {
  id: string;
  text: string;
  options: Array<{
    label: string;
    next?: string;
    level?: string;
  }>;
}

export interface TriageResult {
  severity: string;
  notifyManagement?: boolean;
  primaryService: { id: string; name: string } | null;
  secondaryService: { id: string; name: string } | null;
  schoolActions: string[];
  summaryTag?: string;
  uiFlags?: {
    confidential?: boolean;
    showGuardrail?: boolean;
    avoidRetraumatization?: boolean;
  };
}

export interface Service {
  id: string;
  name: string;
  type: string;
  tags?: string[];
  address: string;
  phone: string;
  coordinates: {
    lat: number;
    lng: number;
  };
  mapPinColor: string;
  priorityLevel: number;
}

export interface OrientationBlock {
  id: string;
  title: string;
  content: string[];
}
