export interface AppModel {
  version: string;
  meta: {
    appName: string;
    version: string;
    scope: string;
    guardrailEnabled: boolean;
    emergencyButton?: {
      label: string;
      color: string;
      fixed: boolean;
      priorityRouteIds: string[];
    };
  };
  searchConfig?: {
    mode: string;
    includeSynonyms: boolean;
    fieldsIndexed: string[];
  };
  uiConfig?: {
    designStyle: string;
    cardsRounded: boolean;
    shadowSoft: boolean;
    maxQuestionsPerFlow: number;
    resultLayout: {
      primaryServiceFirst: boolean;
      secondaryServiceVisible: boolean;
      collapsibleGuidelines: boolean;
      institutionalSummaryAutoGenerated: boolean;
    };
  };
  guardrail: {
    questions: GuardrailQuestion[];
  };
  categories: Category[];
  flows: Flow[];
  services: Service[];
  orientationBlocks: OrientationBlock[];
  summaryTemplate: {
    title: string;
    structure: string[];
  };
  institution: {
    name: string;
    managementContact: {
      name: string;
      phone: string;
      email: string;
    };
  };
}

export type RiskGroup =
  | 'violence'
  | 'psychosocial'
  | 'medical'
  | 'social'
  | 'rights'
  | 'structural'
  | 'emergency';

export interface GuardrailQuestion {
  id: string;
  text: string;
  type: 'boolean';
  ifTrue: string;
}

export interface Category {
  id: string;
  label: string;
  riskGroup: RiskGroup;
  description?: string;
  icon: string;
  color?: string;
  weight?: number;
  subcategories: Array<{ id: string; label: string }>;
  isEmergencyCategory?: boolean;
}

export interface Flow {
  meta: {
    id: string;
    categoryId: string; // Added to maintain relationship
    subcategoryId?: string;
    subcategory: string;
    severity?: 'CRITICAL' | 'HIGH' | 'MODERATE';
    type: 'standard' | 'medical_emergency' | 'security_emergency';
    title: string;
    keywords: string[];
  };
  riskModel: {
    usedLevels: string[];
    defaultLevel: string;
  };
  triage: {
    maxQuestions: number;
    questions: TriageQuestion[];
  };
  results: Record<string, TriageResult>;
}

export type FlowPriority =
  | 'low'
  | 'moderate'
  | 'high'
  | 'critical'
  | 'P0'
  | 'P1'
  | 'P2'
  | 'P3';

// Prioridade institucional — valores semânticos para UI e motor
export type InstitutionalPriority = 'low' | 'moderate' | 'high' | 'critical';

// Código legado — manter apenas para compatibilidade de serialização
export type LegacyPriorityCode = 'P0' | 'P1' | 'P2' | 'P3';

// Mapper explícito e único — USE ESTE em vez de conversão inline
export function toInstitutionalPriority(
  code: LegacyPriorityCode | string
): InstitutionalPriority {
  const map: Record<string, InstitutionalPriority> = {
    P0: 'critical', P1: 'high', P2: 'moderate', P3: 'low'
  };
  return map[code] ?? 'low';
}

// Mapa de exibição PT-BR — USE ESTE para todo texto visível ao usuário
export const PRIORITY_LABELS: Record<InstitutionalPriority, string> = {
  low: 'Atenção',
  moderate: 'Atenção Elevada',
  high: 'Alto Risco',
  critical: 'Crítico — Ação Imediata'
};

export interface TriageQuestion {
  id: string;
  text: string;
  options: Array<{
    label: string;
    next?: string;
    level?: string;
    nextFlow?: string;
    redirectToCategories?: boolean;
  }>;
}

export interface TriageResult {
  level?: string;
  severity: string;
  priority?: FlowPriority;
  notifyManagement?: boolean;
  primaryService: { id: string; name: string } | null;
  secondaryService: { id: string; name: string } | null;
  schoolActions: string[];
  explanationPoints?: string[];
  institutionalScript?: string[];
  appliedRules?: string[];
  riskScore?: number;
  riskScoreFactors?: string[];
  summaryTag?: string;
  uiFlags?: {
    confidential?: boolean;
    showGuardrail?: boolean;
    avoidRetraumatization?: boolean;
  };
}

export interface Service {
  id: string;
  name: string;
  category: string;
  type: string;
  /**
   * Calculated availability metadata derived from the `contact` object.
   * All values are optional to preserve compatibility with legacy datasets.
   */
  contactAvailability?: {
    /** Indicates if the service has a primary phone number. */
    hasPhone: boolean;
    /** Indicates if the service has an alternate phone number. */
    hasAlternate: boolean;
    /** Indicates if the service has an email contact channel. */
    hasEmail: boolean;
    /** Indicates if the service has a website URL. */
    hasWebsite: boolean;
    /** Percentage score (0-100) of available contact channels. */
    completenessScore: number;
  };
  /**
   * Marks entries that require geolocation validation/review.
   */
  needsGeoReview?: boolean;
  contact: {
    phone: string | null;
    /** Optional list of extra phone numbers for expanded contact coverage. */
    otherPhones?: string[];
    email?: string | null;
    website?: string | null;
    alternatePhone?: string | null;
  };
  location: {
    name?: string;
    address: string;
    lat: number | null;
    lng: number | null;
  };
}

export interface NetworkLayer {
  id: string;
  label: string;
  serviceIds: string[];
  icon: string;
  color: string;
  /** 0 means highest urgency. */
  priority: number;
  style: 'solid' | 'glow';
  defaultVisible: boolean;
}

export interface NetworkConfig {
  layers: Record<string, NetworkLayer>;
  schoolReference?: {
    name: string;
    lat: number;
    lng: number;
    proximityRadiusMeters: number;
  };
}

export interface OrientationBlock {
  id: string;
  title: string;
  content: string[];
}

export interface TriageSession {
  flowId: string;
  categoryId: string;
  startedAt: number;
  updatedAt: number;
  completedAt?: number;
  status: 'in_progress' | 'completed' | 'aborted';
  isComplete: boolean;
  result: TriageResult | null;
}
