export interface AppModel {
  meta: {
    appName: string;
    version: string;
    scope: string;
    guardrailEnabled: boolean;
    emergencyButton?: {
      label: string;
      color: string;
      fixed: boolean;
      priorityRouteIds: string[];
    };
  };
  searchConfig?: {
    mode: string;
    includeSynonyms: boolean;
    fieldsIndexed: string[];
  };
  uiConfig?: {
    designStyle: string;
    cardsRounded: boolean;
    shadowSoft: boolean;
    maxQuestionsPerFlow: number;
    resultLayout: {
      primaryServiceFirst: boolean;
      secondaryServiceVisible: boolean;
      collapsibleGuidelines: boolean;
      institutionalSummaryAutoGenerated: boolean;
    };
  };
  guardrail: {
    questions: GuardrailQuestion[];
  };
  categories: Category[];
  flows: Flow[];
  services: Service[];
  orientationBlocks: OrientationBlock[];
  summaryTemplate: {
    title: string;
    structure: string[];
  };
  institution: {
    name: string;
    managementContact: {
      name: string;
      phone: string;
      email: string;
    };
  };
}

export type RiskGroup =
  | 'violence'
  | 'psychosocial'
  | 'medical'
  | 'social'
  | 'rights'
  | 'structural'
  | 'emergency';

export interface GuardrailQuestion {
  id: string;
  text: string;
  type: 'boolean';
  ifTrue: string;
}

export interface Category {
  id: string;
  label: string;
  riskGroup: RiskGroup;
  description?: string;
  icon: string;
  color?: string;
  weight?: number;
  subcategories: Array<{ id: string; label: string }>;
  isEmergencyCategory?: boolean;
}

export interface Flow {
  meta: {
    id: string;
    categoryId: string; // Added to maintain relationship
    subcategoryId?: string;
    subcategory: string;
    severity?: 'CRITICAL' | 'HIGH' | 'MODERATE';
    type: 'standard' | 'medical_emergency' | 'security_emergency';
    title: string;
    keywords: string[];
  };
  riskModel: {
    usedLevels: string[];
    defaultLevel: string;
  };
  triage: {
    maxQuestions: number;
    questions: TriageQuestion[];
  };
  results: Record<string, TriageResult>;
}

export interface TriageQuestion {
  id: string;
  text: string;
  options: Array<{
    label: string;
    next?: string;
    level?: string;
    nextFlow?: string;
    redirectToCategories?: boolean;
  }>;
}

export interface TriageResult {
  level?: string; // NOVO — necessário para motor premium
  severity: string;
  notifyManagement?: boolean;
  primaryService: { id: string; name: string } | null;
  secondaryService: { id: string; name: string } | null;
  schoolActions: string[];
  summaryTag?: string;
  uiFlags?: {
    confidential?: boolean;
    showGuardrail?: boolean;
    avoidRetraumatization?: boolean;
  };
}

export interface Service {
  id: string;
  name: string;
  category: string;
  type: string;
  /**
   * Calculated availability metadata derived from the `contact` object.
   * All values are optional to preserve compatibility with legacy datasets.
   */
  contactAvailability?: {
    /** Indicates if the service has a primary phone number. */
    hasPhone: boolean;
    /** Indicates if the service has an alternate phone number. */
    hasAlternate: boolean;
    /** Indicates if the service has an email contact channel. */
    hasEmail: boolean;
    /** Indicates if the service has a website URL. */
    hasWebsite: boolean;
    /** Percentage score (0-100) of available contact channels. */
    completenessScore: number;
  };
  /**
   * Marks entries that require geolocation validation/review.
   */
  needsGeoReview?: boolean;
  contact: {
    phone: string | null;
    /** Optional list of extra phone numbers for expanded contact coverage. */
    otherPhones?: string[];
    email?: string | null;
    website?: string | null;
    alternatePhone?: string | null;
  };
  location: {
    name?: string;
    address: string;
    lat: number | null;
    lng: number | null;
  };
}

export interface NetworkLayer {
  id: string;
  label: string;
  serviceIds: string[];
  icon: string;
  color: string;
  /** 0 means highest urgency. */
  priority: number;
  style: 'solid' | 'glow';
  defaultVisible: boolean;
}

export interface NetworkConfig {
  layers: Record<string, NetworkLayer>;
  schoolReference?: {
    name: string;
    lat: number;
    lng: number;
    proximityRadiusMeters: number;
  };
}

/**
 * Example structure demonstrating a `Service` with the expanded contact model.
 */
export const serviceExample: Service = {
  id: 'service-001',
  name: 'Centro de Apoio Psicossocial',
  category: 'psychosocial',
  type: 'public',
  needsGeoReview: false,
  contact: {
    phone: '(11) 4002-8922',
    alternatePhone: '(11) 98888-0000',
    otherPhones: ['(11) 3000-0000', '(11) 97777-1111'],
    email: 'contato@caps.exemplo.br',
    website: 'https://caps.exemplo.br',
  },
  contactAvailability: {
    hasPhone: true,
    hasAlternate: true,
    hasEmail: true,
    hasWebsite: true,
    completenessScore: 100,
  },
  location: {
    name: 'Unidade Centro',
    address: 'Rua Exemplo, 123 - Centro',
    lat: -23.55052,
    lng: -46.633308,
  },
};

/**
 * Calculates a 0-100 score based on the contact channels available in a service.
 */
export function calculateContactCompleteness(service: Service): number {
  const checks = [
    Boolean(service.contact.phone),
    Boolean(service.contact.alternatePhone),
    Boolean(service.contact.email),
    Boolean(service.contact.website),
  ];

  const available = checks.filter(Boolean).length;
  return Math.round((available / checks.length) * 100);
}

export interface OrientationBlock {
  id: string;
  title: string;
  content: string[];
}
